version: '1.1'
services:
  nginx:
    container_name: nginx_shortener
    image: nginx:1.21-alpine
    build: ./nginx_docker      
    ports:
      - "89:80"         
    environment:
      - discovery.type=single-node 
    networks:
      - nginx_network   
      
networks:
  nginx_network:
    driver: bridge          
