FROM postgres:13.0

ENV POSTGRES_DB shortener_db
ENV POSTGRES_USER shortner_user
ENV POSTGRES_PASSWORD sh()rTner_8S

ENV PGDATABASE shortener_db
ENV PGUSER shortner_user
ENV PGPASSWORD sh()rTner_8S


COPY schema_db.sql /docker-entrypoint-initdb.d
